#!/usr/bin/env python3
"""svg_to_ilda_with_center.py

Variant of ``svg_to_ilda.py`` that adds the tracked offsets from
``pc_generation/center.yaml`` on top of the user-provided ``--offset-x`` and
``--offset-y`` values before streaming to the Helios DAC.
"""

from __future__ import annotations

import argparse
import ctypes
import re
import sys
from pathlib import Path


TARGET_MAX = 4095
HeliosLib = ctypes.cdll.LoadLibrary("./libHeliosDacAPI.so")


class HeliosPoint(ctypes.Structure):
    _fields_ = [
        ("x", ctypes.c_uint16),
        ("y", ctypes.c_uint16),
        ("r", ctypes.c_uint8),
        ("g", ctypes.c_uint8),
        ("b", ctypes.c_uint8),
        ("i", ctypes.c_uint8),
    ]


sys.path.append(str(Path(__file__).parent))
try:
    from convert_svg_to_points import process_svg
except Exception as e:
    sys.stderr.write(f"Failed to import conversion module: {e}\n")
    sys.exit(1)


def mirror_vertical(points):
    return [(TARGET_MAX - x, TARGET_MAX - y, pen) for (x, y, pen) in points]


def simplify_points(points, max_points=1000, tolerance_degrees=5):
    import math

    if len(points) <= 2:
        return points
    kept = [points[0]]
    for i in range(1, len(points) - 1):
        x0, y0, p0 = kept[-1]
        x1, y1, p1 = points[i]
        x2, y2, p2 = points[i + 1]
        if p1 != p0:
            kept.append(points[i])
            continue
        dx1, dy1 = x1 - x0, y1 - y0
        dx2, dy2 = x2 - x1, y2 - y1
        if (dx1 == 0 and dy1 == 0) or (dx2 == 0 and dy2 == 0):
            kept.append(points[i])
            continue
        ang1 = math.degrees(math.atan2(dy1, dx1))
        ang2 = math.degrees(math.atan2(dy2, dx2))
        diff = abs(ang2 - ang1)
        if diff > 180:
            diff = 360 - diff
        if diff > tolerance_degrees:
            kept.append(points[i])
    kept.append(points[-1])
    return kept


def build_helios_frame(points, r, g, b):
    frame_type = HeliosPoint * len(points)
    frame = frame_type()
    for idx, (x, y, pen) in enumerate(points):
        frame[idx] = HeliosPoint(int(x), int(y), r, g, b, int(pen))
    return frame


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert SVG to ILDA frame, adding offsets from center.yaml."
    )
    parser.add_argument("svg_file", help="Path to the input SVG file")
    parser.add_argument(
        "--center-yaml",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "pc_generation" / "center.yaml",
        help="Path to the center.yaml file generated by point-cloud tracking.",
    )
    parser.add_argument(
        "--scale",
        "-s",
        type=float,
        default=100.0,
        help="Scaling factor as a percentage (100 = original size)",
    )
    parser.add_argument(
        "--tolerance",
        "-t",
        type=float,
        default=5.0,
        help="Angle tolerance in degrees for simplification (default 5)",
    )
    parser.add_argument(
        "--offset-x",
        type=float,
        default=0.0,
        help="Base horizontal offset before adding center.yaml offset_x_px",
    )
    parser.add_argument(
        "--offset-y",
        type=float,
        default=0.0,
        help="Base vertical offset before adding center.yaml offset_y_px",
    )
    parser.add_argument("--red", type=int, default=0, help="Red component (default 0)")
    parser.add_argument("--green", type=int, default=93, help="Green component (default 93)")
    parser.add_argument("--blue", type=int, default=0, help="Blue component (default 0)")
    return parser.parse_args()


def read_center_offsets(center_yaml: Path) -> tuple[float, float]:
    if not center_yaml.is_file():
        raise RuntimeError(f"center.yaml file not found: {center_yaml}")

    text = center_yaml.read_text(encoding="utf-8")
    status_match = re.search(r"^status:\s*(.+?)\s*$", text, re.MULTILINE)
    if not status_match:
        raise RuntimeError(f"Could not read status from {center_yaml}")
    status = status_match.group(1).strip()
    if status != "ok":
        raise RuntimeError(f"center.yaml status is not ok: {status}")

    def extract_scalar(name: str) -> float:
        match = re.search(rf"^{re.escape(name)}:\s*([-+0-9.eE]+)\s*$", text, re.MULTILINE)
        if not match:
            raise RuntimeError(f"Could not read {name} from {center_yaml}")
        return float(match.group(1))

    return extract_scalar("offset_x_px"), extract_scalar("offset_y_px")


def apply_scale_and_offset(
    points: list[tuple[int, int, int]],
    scale_factor: float,
    offset_x: float,
    offset_y: float,
) -> list[tuple[int, int, int]]:
    transformed = []
    for x, y, pen in points:
        sx = int(round(x * scale_factor))
        sy = int(round(y * scale_factor))
        ox = int(round(sx + offset_x))
        oy = int(round(sy + offset_y))
        ox = max(0, min(TARGET_MAX, ox))
        oy = max(0, min(TARGET_MAX, oy))
        transformed.append((ox, oy, pen))
    return transformed


def main():
    args = parse_args()
    svg_path = args.svg_file
    if not Path(svg_path).is_file():
        sys.stderr.write(f"File not found: {svg_path}\n")
        sys.exit(1)

    points = process_svg(svg_path)
    if not points:
        sys.stderr.write("No points generated from SVG.\n")
        sys.exit(1)

    scale_factor = args.scale / 100.0

    num_devices = HeliosLib.OpenDevices()
    if num_devices == 0:
        sys.stderr.write("No Helios DAC devices found.\n")
        sys.exit(1)

    device_index = 0
    total_offset_x = args.offset_x
    total_offset_y = args.offset_y
    center_offset_x = 0.0
    center_offset_y = 0.0
    optimized_points = []
    for _ in range(15000):
        center_offset_x, center_offset_y = read_center_offsets(args.center_yaml)
        total_offset_x = args.offset_x + center_offset_x * args.scale
        total_offset_y = args.offset_y + center_offset_y * args.scale

        transformed_points = apply_scale_and_offset(
            points,
            scale_factor,
            total_offset_x,
            total_offset_y,
        )
        mirrored = mirror_vertical(transformed_points)
        optimized_points = simplify_points(
            mirrored,
            max_points=1000,
            tolerance_degrees=args.tolerance,
        )
        frame = build_helios_frame(optimized_points, args.red, args.green, args.blue)

        status_attempts = 0
        while status_attempts < 512 and HeliosLib.GetStatus(0) != 1:
            status_attempts += 1
        HeliosLib.WriteFrame(
            device_index,
            ctypes.c_uint32(30000),
            ctypes.c_uint32(0),
            ctypes.pointer(frame),
            ctypes.c_uint32(len(optimized_points)),
        )
    HeliosLib.CloseDevices()
    print(
        f"Wrote {len(optimized_points)} points (optimized) to device {device_index}. "
        f"Applied offsets: base=({args.offset_x:.1f}, {args.offset_y:.1f}) "
        f"+ center=({center_offset_x:.1f}, {center_offset_y:.1f}) "
        f"=> total=({total_offset_x:.1f}, {total_offset_y:.1f})"
    )


if __name__ == "__main__":
    main()
